#### White Blood cells/ul Z-scores
```{r}
test <- cont %>% filter(Treatment == 'Control H1N1' |  Treatment == 'Antibiotic H1N1')
```

```{r echo=F}
fit=lmerTest::lmer(WBC_zscore ~ ns(infection_day, df=5)*Treatment+(1|animal_number),data=test)
```

```{r echo=FALSE}
p=plot_model(fit, type = "pred",title ="", terms = c("infection_day [all]", 'Treatment'), colors = c("darkred", "darkblue"), show.data=TRUE) + theme_classic() + theme(text = element_text(size=20))
p_res = plot_redres(fit, type = "std_cond")
dir = file.path("figures", "cbc", "wbc-zscores.tiff")
ggsave(dir, plot = p, width = 12, height = 5, units = "in", compression = "lzw")
p
```

```{r echo=F}
dt <- anova(fit)
# LaTeX Table
kbl(dt, booktabs = T, digits = 3, caption = "Total WBC Z score") %>%
  kable_styling(latex_options = c("striped", "hold_position",  font_size = 16, html_font = "arial"))
```

### Polymononuclear Cells/ul z-scores

```{r echo=F}
fit=lmerTest::lmer(PMN_zscore ~ ns(infection_day, df=5)*Treatment +(1|animal_number),data=test)
```

```{r echo=FALSE}
p=plot_model(fit, type = "pred",title ="", terms = c("infection_day [all]", 'Treatment'), colors = c("darkred", "darkblue"), show.data=TRUE) + theme_classic() + theme(text = element_text(size=20))
p_res = plot_redres(fit, type = "std_cond")
dir = file.path("figures", "cbc", "NLR-zscores.tiff")
ggsave(dir, plot = p, width = 12, height = 5, units = "in", compression = "lzw")
p
```

```{r echo=F}
dt <- anova(fit)
# LaTeX Table
kbl(dt, booktabs = T, digits = 3, caption = "PMN Concentration Z score") %>%
  kable_styling(latex_options = c("striped", "hold_position",  font_size = 16, html_font = "arial"))
```

### Lymphoyctes/ul z-scores

```{r echo=F}
fit=lmerTest::lmer(Lymph_zscore ~ ns(infection_day, df=5)*Treatment +(1|animal_number),data=test )
```

```{r echo=FALSE}
p=plot_model(fit, type = "pred",title ="", terms = c("infection_day [all]", 'Treatment'), colors = c("darkred", "darkblue"), show.data=TRUE) + theme_classic() + theme(text = element_text(size=20))
p_res = plot_redres(fit, type = "std_cond")
dir = file.path("figures", "cbc", "lymphocytes-zscores.tiff")
ggsave(dir, plot = p, width = 12, height = 5, units = "in", compression = "lzw")
p
```

```{r echo=F}
dt <- anova(fit)
# LaTeX Table
kbl(dt, booktabs = T, digits = 3, caption = "Lymphocyte Concentration Z score") %>%
  kable_styling(latex_options = c("striped", "hold_position",  font_size = 16, html_font = "arial"))
```

### Monocytes/ul z-scores

```{r echo=F}
fit=lmerTest::lmer(Mono_zscore ~ ns(infection_day, df=5)*Treatment +(1|animal_number),data=test)
```

```{r echo=FALSE}
p=plot_model(fit, type = "pred",title ="", terms = c("infection_day [all]", 'Treatment'), colors = c("darkred", "darkblue"), show.data=TRUE) + theme_classic() + theme(text = element_text(size=20))
p_res = plot_redres(fit, type = "std_cond")
dir = file.path("figures", "cbc", "monocytes-zscores.tiff")
ggsave(dir, plot = p, width = 12, height = 5, units = "in", compression = "lzw")
p
```

```{r echo=F}
dt <- anova(fit)
# LaTeX Table
kbl(dt, booktabs = T, digits = 3, caption = "Monocyte Concentration Z score") %>%
  kable_styling(latex_options = c("striped", "hold_position",  font_size = 16, html_font = "arial"))
```

### Eosinophils/ul z scores

```{r echo=F}
fit=lmerTest::lmer(Eos_zscore ~ ns(infection_day, df=5)*Treatment+(1|animal_number),data=test)
```

```{r echo=FALSE}
p=plot_model(fit, type = "pred",title ="", terms = c("infection_day [all]", 'Treatment'), colors = c("darkred", "darkblue"),  show.data=TRUE) + theme_classic() + theme(text = element_text(size=20))
p_res = plot_redres(fit, type = "std_cond")
dir = file.path("figures", "cbc", "eosinophil-zscores.tiff")
ggsave(dir, plot = p, width = 12, height = 5, units = "in", compression = "lzw")
p
```

```{r echo=F}
dt <- anova(fit)
# LaTeX Table
kbl(dt, booktabs = T, digits = 3, caption = "Eosinophil Concentration Z score") %>%
  kable_styling(latex_options = c("striped", "hold_position",  font_size = 16, html_font = "arial"))
```

### Neutrophil to Lymphocte ratio z scores

```{r echo=F}
fit=lmerTest::lmer(NLR_zscore ~ ns(infection_day, df=5)*Treatment+(1|animal_number),data=test)
```

```{r echo=FALSE}
p=plot_model(fit, type = "pred",title ="", terms = c("infection_day [all]", 'Treatment'), colors = c("darkred", "darkblue"), show.data=TRUE) + theme_classic() + theme(text = element_text(size=20))
p_res = plot_redres(fit, type = "std_cond")
dir = file.path("figures", "cbc", "NLR-zscores.tiff")
ggsave(dir, plot = p, width = 12, height = 5, units = "in", compression = "lzw")
p
```

```{r echo=F}
dt <- anova(fit)
# LaTeX Table
kbl(dt, booktabs = T, digits = 3, caption = "Neutrophil to Lymphocyte Ratio Z score") %>%
  kable_styling(latex_options = c("striped", "hold_position",  font_size = 16, html_font = "arial"))
```
