---
title: "CBC Splines"
author: 
  - Noah Siegel
date: "`r format(Sys.time(), '%d %B, %Y, %H:%M')`"
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "documents") })
output:
  pdf_document:
     includes:
        in_header: style.sty
---

```{r environment, include=F}
# Set up global options for nice reports and keeping figures:
knitr::opts_chunk$set(fig.width=14, fig.height=8, fig.align="center", dev = 'png',
                      warning=FALSE, message=FALSE)
```

```{r}
suppressPackageStartupMessages({
  library(tidyverse)
  library(sjPlot)
  library(lmerTest)
  library(readxl)
  library(xlsx)
  library(kableExtra)
  library(splines)
  library(redres)
})
```

```{r directory, include=F}
dir.create('figures/cbc/h1n1', showWarnings = FALSE)
dir.create('figures/cbc/fmt', showWarnings = FALSE)
```

```{r include=F}
#source("R/download-data.R")
source("R/functions.R")
source("R/cbc-zscores.R", local = TRUE)
```

```{r echo=F}
# format metadata for publication
cont$treatment <- as.character(cont$treatment)
cont$sex <- as.character(cont$sex)
names(cont)[names(cont)=="treatment"] <- "Treatment"
names(cont)[names(cont)=="sex"] <- "Sex"
cont$Treatment[cont$Treatment == "control"] <- "Control"
cont$Treatment[cont$Treatment == "abx"] <- "Antibiotic"
cont$Treatment[cont$Treatment == "abx_fmt"] <- "Antibiotic FMT"
cont$Treatment[cont$Treatment == "control_H1N1"] <- "Control H1N1"
cont$Treatment[cont$Treatment == "abx_H1N1"] <- "Antibiotic H1N1"
```

```{r echo=F}
cont$Sex[cont$Sex == "M"] <- "Males"
cont$Sex[cont$Sex == "F"] <- "Females"
cont$Treatment <- factor(cont$Treatment)
cont$Sex <- factor(cont$Sex)
```

# H1N1 Control vs. Antibiotic

```{r H1N1-Control-vs-ABX-animals, child = '1.1_h1n1.rmd'}
```

# FMT vs. Antibiotic

```{r FMT-vs.-ABX-animals, child = '1.2_fmt.rmd'}
```

# Session Information

```{r echo=F}
sessionInfo()
```
