#!/bin/bash

# Stop on fail!
set -e

Rscript - <<'EOF'
    library('devtools')
    devtools::install_github('goodekat/redres@714227e', upgrade = 'never', dependencies = TRUE)
    devtools::install_github('RRShieldsCutler/splinectomeR@a644068', upgrade = 'never')
EOF
