if(!require(remotes)){
  install.packages("remotes")
  library(remotes)
}
if(!require(devtools)){
  install.packages("devtools")
  library(devtools)
}
if(!require(broom.mixed)){
  install.packages("broom.mixed")
  library("broom.mixed")
}
if(!require(glmmTMB)){
  install.packages("glmmTMB")
  library(glmmTMB)
}
if(!require(tidyr)){
  install.packages("tidyr")
  library(tidyr)
}
if(!require(stringr)){
  install.packages("stringr")
  library('stringr')
}
if(!require(reshape2)){
  install.packages("reshape2")
  library('reshape2')
}
if(!require(openxlsx)){
  install.packages("openxlsx")
  library("openxlsx")
}
if(!require(readxl)){
  install.packages("readxl")
  library("readxl")
}
if(!require(plyr)){
  install.packages("plyr")
  library("plyr")
}
if(!require(dplyr)){
  install.packages("dplyr")
  library("dplyr")
}
if(!require(kableExtra)){
  install.packages("kableExtra")
  library("kableExtra")
}
if(!require(knitr)){
  install_version("knitr", "1.31")
  library("knitr")
}

#zscore packages
if(!require(emmeans)){
  remotes::install_github("rvlenth/emmeans")
  library("emmeans")
}
if(!require(afex)){
  install.packages("afex")
  library("afex")
}
if(!require(ggplot2)){
  install.packages("ggplot2")
  library("ggplot2")
}
if(!require(sjPlot)){
  install.packages("sjPlot")
  library("sjPlot")
}
if(!require(flextable)){
  install.packages("flextable")
  library("flextable")
}
if(!require(kableExtra)){
  install.packages("kableExtra")
  library("kableExtra")
}
if(!require(magick)){
  install.packages("magick")
  library("magick")
}
if(!require(webshot)){
  install.packages("webshot")
  library("webshot")
}
if(!require(ggpubr)){
  install.packages("ggpubr")
  library("ggpubr")
}
if(!require(rstatix)){
  install.packages("rstatix")
  library("rstatix")
}
if(!require(glmmTMB)){
  devtools::install_github("glmmTMB/glmmTMB/glmmTMB")
  library("glmmTMB")
}